# BACKGROUND
background {
    monitor =
    path = ~/dotfiles/wallpapers/Goku.jpg
    # blur_passes = 3
    # blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

# SIDEBAR PANEL
shape {
    monitor =
    size = 600, 70%
    color = rgba(0, 0, 0, 0.5) # Mocha Crust/Base mix
    rounding = 0
    border_size = 0
    position = -100, 0
    halign = right
    valign = center
}

# TIME (Top Left)
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M:%S %p")</span>"
    color = rgba(205, 214, 244, 1.0) # Text
    font_size = 60
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = -120, -200
    halign = right
    valign = top
}

# DAY/DATE
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%A")</span>"
    color = rgba(203, 166, 247, 1.0) # Mauve
    font_size = 35
    font_family = JetBrainsMono Nerd Font Bold
    position = -120, -300
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%d %B %Y")</span>"
    color = rgba(166, 227, 161, 0.6) # Green
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = -120, -370
    halign = right
    valign = top
}

# Profile Picture
# image {
#     monitor =
#     path = ~/dotfiles/wallpapers/Goku.jpg
#     size = 180
#     rounding = -1
#     border_size = 4
#     border_color = rgba(203, 166, 247, 1.0)
#     position = 45, -340
#     halign = left
#     valign = top
# }

# Music
# label {
#     monitor =
#     text = cmd[update:1000] echo "$(playerctl metadata --format '{{artist}} - {{title}}' || echo 'No media playing')"
#     color = rgba(137, 180, 250, 0.8)
#     font_size = 15
#     font_family = JetBrainsMono Nerd Font
#     position = 45, -550
#     halign = left
#     valign = top
# }

# USER INFO
label {
    monitor =
    text = Welcome back, $USER
    color = rgba(205, 214, 244, 0.7)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = -190, 260
    halign = right
    valign = bottom
}

# INPUT FIELD (Bottom Left)
input-field {
    monitor =
    size = 350, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(203, 166, 247, 0)
    inner_color = rgba(30, 30, 46, 0.5)
    font_color = rgba(205, 214, 244, 1.0)
    fade_on_empty = false
    rounding = 10
    placeholder_text = <span foreground="##cdd6f488">  Password</span>
    hide_input = false
    position = -120, 190
    halign = right
    valign = bottom
    check_color = rgba(166, 227, 161, 1.0)
    fail_color = rgba(243, 139, 168, 1.0)
}

# BATTERY (Bottom Right of Sidebar)
label {
    monitor =
    text = cmd[update:1000] echo -e "$(cat /sys/class/power_supply/BAT0/capacity)%"
    color = rgba(147, 153, 178, 1.0)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 50, 20
    halign = left
    valign = bottom
}
